AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an Amazon Bedrock Agent (without action group)'

Parameters:
  BedrockModelId:
    Type: String
    Default: anthropic.claude-3-sonnet-20240229-v1:0
    Description: The Bedrock model ID to use for the agent
  
  AgentName:
    Type: String
    Default: MyBedrockAgent
    Description: Name for the Bedrock Agent
    
  AgentInstruction:
    Type: String
    Default: "You are a helpful assistant that can help users with various tasks."
    Description: System prompt/instruction for the Bedrock Agent
    AllowedPattern: ".+"
    ConstraintDescription: The instruction cannot be empty

Resources:
  # IAM Role for Bedrock Agent
  BedrockAgentRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonBedrockFullAccess'
      Policies:
        - PolicyName: BedrockAgentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'bedrock:*'
                  - 'lambda:InvokeFunction'
                  - 'cloudwatch:PutMetricData'
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
      
  # Bedrock Agent
  BedrockAgent:
    Type: 'AWS::Bedrock::Agent'
    Properties:
      AgentName: !Ref AgentName
      FoundationModel: !Ref BedrockModelId
      AgentResourceRoleArn: !GetAtt BedrockAgentRole.Arn
      Description: "Agent created via CloudFormation"
      IdleSessionTTLInSeconds: 1800
      Instruction: !Ref AgentInstruction

  # Bedrock Agent Alias
  BedrockAgentAlias:
    Type: 'AWS::Bedrock::AgentAlias'
    Properties:
      AgentId: !Ref BedrockAgent
      AgentAliasName: 'prod'
      Description: 'Production alias for the agent'

Outputs:
  BedrockAgentId:
    Description: The ID of the created Bedrock Agent
    Value: !Ref BedrockAgent
  
  BedrockAgentAliasId:
    Description: The ID of the created Bedrock Agent Alias
    Value: !Ref BedrockAgentAlias